services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    expose:
      - "3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
       redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    env_file: ./docker.env
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  https-ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "outline:3000"
      - "--domain=nonturbinate-johnnie-unmarketed.ngrok-free.dev"
    depends_on:
      - outline
    restart: always
    environment:
      NGROK_AUTHTOKEN: '34ILpzy2RDfXwh2PC75CgeLbdlv_5vuZQoevDEbYQb4zWkFcH'

volumes:
  storage-data: