services:
  - type: web
    name: outline-app
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
